
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nada0038/order-service-l8:latest
          ports:
            - containerPort: 3000
          env:
            - name: ORDER_QUEUE_HOSTNAME
              value: rabbitmq
            - name: ORDER_QUEUE_PORT
              value: "5672"
            - name: ORDER_QUEUE_USERNAME
              value: username
            - name: ORDER_QUEUE_PASSWORD
              value: password
            - name: ORDER_QUEUE_NAME
              value: orders
            - name: FASTIFY_ADDRESS
              value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
        - name: makeline-service
          image: nada0038/makeline-service-l8:latest
          ports:
            - containerPort: 3001
          env:
            - name: ORDER_QUEUE_URI
              value: amqp://rabbitmq:5672
            - name: ORDER_QUEUE_USERNAME
              value: username
            - name: ORDER_QUEUE_PASSWORD
              value: password
            - name: ORDER_QUEUE_NAME
              value: orders
            - name: ORDER_DB_URI
              value: mongodb://mongodb:27017
            - name: ORDER_DB_NAME
              value: orderdb
            - name: ORDER_DB_COLLECTION_NAME
              value: orders
---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  selector:
    app: makeline-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: nada0038/product-service-l8:latest
          ports:
            - containerPort: 3002
          env:
            - name: AI_SERVICE_URL
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
        - name: store-front
          image: nada0038/store-front-l8:latest
          ports:
            - containerPort: 8080
          env:
            - name: VUE_APP_ORDER_SERVICE_URL
              value: http://order-service:3000/
            - name: VUE_APP_PRODUCT_SERVICE_URL
              value: http://product-service:3002/
---
apiVersion: v1
kind: Service
metadata:
  name: store-front
spec:
  selector:
    app: store-front
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: nada0038/store-admin-l8:latest
          ports:
            - containerPort: 8081
          env:
            - name: VUE_APP_PRODUCT_SERVICE_URL
              value: http://product-service:3002/
            - name: VUE_APP_MAKELINE_SERVICE_URL
              value: http://makeline-service:3001/
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  selector:
    app: store-admin
  ports:
    - name: http
      port: 80
      targetPort: 8081
  type: LoadBalancer
